services:
  sqlserver:
    build: .   # <--- usa o Dockerfile da raiz
    container_name: sqlserver-hack
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - ./init-db:/init-db
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        pid=$!;
        echo '⏳ Aguardando SQL Server iniciar...';
        sleep 25;
        echo '▶️ Executando init.sql...';
        sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -i /init-db/init.sql;
        wait $pid
      "
    restart: always
