# Datasource LOCAL (H2)  TESTE CAIXA
# ================================
#quarkus.datasource.local.db-kind=h2
#quarkus.datasource.local.username=hack
#quarkus.datasource.local.password=Password23
#quarkus.datasource.local.jdbc.url=jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#quarkus.datasource.local.jdbc.driver=org.h2.Driver

# ================================
# Datasource LOCAL (PostgreSQL)
# ================================
# Configuração do datasource LOCAL (PostgreSQL)
quarkus.datasource.local.db-kind=postgresql
#quarkus.datasource.local.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.local.jdbc.url=jdbc:postgresql://postgres:5432/postgres
quarkus.datasource.local.username=postgres
quarkus.datasource.local.password=12345


# Configuração Hibernate ORM LOCAL
quarkus.hibernate-orm.local.datasource=local
quarkus.hibernate-orm.local.packages=gov.caixa.simuladorservice.entity.simulacao
quarkus.hibernate-orm.local.database.generation=update

# ================================
# Datasource EXTERNO (SQL Server) - comentado para teste
# ================================
 quarkus.datasource.external.db-kind=mssql
 quarkus.datasource.external.username=hack
 quarkus.datasource.external.password=Password23
 quarkus.datasource.external.jdbc.url=jdbc:sqlserver://dbhackathon.database.windows.net:1433;databaseName=hack
 quarkus.datasource.external.jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
 quarkus.datasource.external.db-version=12.0.0
 quarkus.hibernate-orm.external.datasource=external
 quarkus.hibernate-orm.external.packages=gov.caixa.simuladorservice.entity.produto
 quarkus.hibernate-orm.external.database.generation=none

# ================================
# Flyway LOCAL
# ================================
quarkus.flyway.local.enabled=true
quarkus.flyway.external.enabled=false
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration/local
quarkus.flyway.datasources=local
quarkus.http.host=0.0.0.0

# Log das queries SQL no console
quarkus.hibernate-orm.log.sql=true

# Desativa Dev Services (não usa Docker para banco)
quarkus.datasource.devservices.enabled=false
quarkus.devservices.enabled=false

# Opções de debug
quarkus.log.category."io.smallrye.jwt".level=WARN
quarkus.log.console.json=true


# ================================
# Circuit Breaker
# ================================
quarkus.log.category."io.smallrye.faulttolerance".level=WARN

# ================================
# JWT
# ================================
mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=https://my-app
quarkus.smallrye-jwt.enabled=true

# ================================
# CORS
# ================================
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=X-Custom-Header
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=86400

# ================================
# Swagger / OpenAPI
# ================================
quarkus.swagger-ui.always-include=true
quarkus.application.name=Simulador de Empréstimos
quarkus.application.version=1.0.0-SNAPSHOT
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Simulador API
quarkus.smallrye-openapi.info-version=1.0.0-SNAPSHOT
quarkus.smallrye-openapi.info-description=API para simular empréstimos com SAC e PRICE
quarkus.smallrye-openapi.info-terms-of-service=http://example.com/terms/
quarkus.smallrye-openapi.info-contact-name=Charles Rodrigues
quarkus.smallrye-openapi.info-contact-email=charles@example.com
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=http://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.path=/swagger-ui

# ================================
# EventHub
# ================================
eventhub.connection-string=${EVENTHUB_CONNECTION_STRING}

# Desliga logs INFO do Azure SDK e AMQP
quarkus.log.category."com.azure".level=WARN
quarkus.log.category."com.azure.core".level=WARN
quarkus.log.category."com.azure.messaging.eventhubs".level=WARN
quarkus.log.category."com.azure.core.amqp".level=WARN
quarkus.log.category."com.azure.core.amqp.impl".level=WARN

# ================================
# Caffeine Cache
# ================================
quarkus.cache.caffeine.simulacoes.maximum-size=1000
quarkus.cache.caffeine.simulacoes.expire-after-write=10M

# ================================
# Métricas
# ================================
quarkus.smallrye-metrics.enabled=true
quarkus.smallrye-metrics.path=/metrics

# ================================
# Logs em arquivo
# ================================
quarkus.log.file.enable=true
quarkus.log.file.path=logs/app.log
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=5

# ================================
# JSON Provider
# ================================
quarkus.resteasy-reactive.jackson.enable=true
quarkus.resteasy-reactive.jsonb.enable=false

quarkus.opentelemetry.tracer.exporter.otlp.enabled=false


