-- Criar o schema dbo (simulado no H2)
CREATE SCHEMA IF NOT EXISTS dbo;

-- Usar o schema dbo
SET SCHEMA dbo;

-- Criar tabela PRODUTO
CREATE TABLE dbo.PRODUTO (
    CO_PRODUTO INT NOT NULL PRIMARY KEY,
    NO_PRODUTO VARCHAR(200) NOT NULL,
    PC_TAXA_JUROS NUMERIC(10, 9) NOT NULL,
    NU_MINIMO_MESES SMALLINT NOT NULL,
    NU_MAXIMO_MESES SMALLINT NULL,
    VR_MINIMO NUMERIC(18, 2) NOT NULL,
    VR_MAXIMO NUMERIC(18, 2) NULL
);

-- Criar tabela SIMULACAO
CREATE TABLE dbo.SIMULACAO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO VARCHAR(255) NOT NULL,
    DATA_SIMULACAO DATE NOT NULL,
    VALOR_SIMULADO NUMERIC(18, 2) NOT NULL,
    TEMPO_RESPOSTA_MS BIGINT NOT NULL,
    VALOR_TOTAL_CREDITO NUMERIC(18, 2),

    VALOR_TOTAL_PARCELAS_SAC NUMERIC(18, 2),
    VALOR_MEDIO_PRESTACAO_SAC NUMERIC(18, 2),
    TAXA_JURO_SAC NUMERIC(5, 4),
    PRAZO_SAC NUMERIC(18, 2),

    VALOR_TOTAL_PARCELAS_PRICE NUMERIC(18, 2),
    VALOR_MEDIO_PRESTACAO_PRICE NUMERIC(18, 2),
    TAXA_JURO_PRICE NUMERIC(5, 4),
    PRAZO_PRICE NUMERIC(18, 2)
);

CREATE TABLE dbo.SIMULACAOTIPO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SIMULACAO_ID BIGINT NOT NULL,
    TIPO_SIMULACAO VARCHAR(20) NOT NULL, -- SAC ou PRICE
    VALOR_TOTAL_PARCELAS NUMERIC(18, 2) NOT NULL,
    VALOR_MEDIO_PRESTACAO NUMERIC(18, 2),
    TAXA_JURO NUMERIC(5, 4),
    PRAZO NUMERIC(18, 2),
    FOREIGN KEY (SIMULACAO_ID) REFERENCES dbo.SIMULACAO(ID)
);


-- Inserir dados na tabela PRODUTO
INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO)
VALUES
(1, 'Produto 1', 0.017900000, 0, 24, 200.00, 10000.00),
(2, 'Produto 2', 0.017500000, 25, 48, 10001.00, 100000.00),
(3, 'Produto 3', 0.018200000, 49, 96, 100000.01, 1000000.00),
(4, 'Produto 4', 0.015100000, 96, NULL, 1000000.01, NULL);
