
-- Criar tabela SIMULACAO para o banco local
CREATE TABLE IF NOT EXISTS dbo.SIMULACAO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO VARCHAR(100),
    DATA_SIMULACAO DATE,
    VALOR_SIMULADO DECIMAL(18,2),
    TEMPO_RESPOSTA_MS BIGINT,
    VALOR_TOTAL_CREDITO DECIMAL(18,2),
    CODIGO_PRODUTO NUMERIC(18, 2)
);

-- Criar tabela SIMULACAOTIPO para o banco local
CREATE TABLE IF NOT EXISTS dbo.SIMULACAOTIPO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SIMULACAO_ID BIGINT NOT NULL,
    TIPO_SIMULACAO VARCHAR(20) NOT NULL,
    VALOR_TOTAL_PARCELAS NUMERIC(18, 2) NOT NULL,
    VALOR_MEDIO_PRESTACAO NUMERIC(18, 2),
    TAXA_JURO NUMERIC(5, 4),
    PRAZO NUMERIC(18, 2),
    FOREIGN KEY (SIMULACAO_ID) REFERENCES SIMULACAO(ID)
);


