name: Build Quarkus App

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Build com Maven
        run: mvn clean install -DskipTests

      - name: Rodar testes
        run: mvn test
