name: Build Quarkus App with SQL Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 30

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache dependências Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # Cache Maven Wrapper
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: |
            .mvn/wrapper
            mvnw
          key: maven-wrapper-${{ hashFiles('mvnw', '.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            maven-wrapper-

      - name: Instalar sqlcmd
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Esperar SQL Server estar pronto
        run: |
          for i in {1..60}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT 1" && break
            echo "Aguardando SQL Server..."
            sleep 2
          done

      - name: Criar banco de dados
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "CREATE DATABASE hack"

      - name: Executar script init.sql
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -d hack -i init-db/init.sql

      - name: Build Maven (sem testes)
        run: ./mvnw clean install -DskipTests -B
